let number1=3;
alert(number1);
let a=10;
let b=2;
alert(a+b);
alert(a-b);
alert(a/b);
alert(a*b);
let c=15;
let d=2;
let result=c+d;
alert(result);
let a1=17;
let b1=10;
let c1=a1-b1;
let d1=7;
let result1=c1+d1;
let str='Hello world!';
alert(str);
let str1='Hello';
let str2='World!';
alert(str1+str2);
let name='Emilija';
alert('Hello,'+name+'!');
let age = 0;
alert('I am '+age+'years old!');
let username=prompt('What is your Name?');
alert('Your name '+username);
